library(tidyverse)
setwd("/Users/ksing/Downloads")
popsize <- read_tsv("pop_size.csv")
library(tibble)
library(ggplot2)
library(dplyr)
library(readr)
popsize
tail(popsize, 10)
glimpse(popsize)
view(popsize)
ndvi <- read_tsv("ndvi.csv")
head(ndvi)
tail(ndvi)
newdata <- select(ndvi, Herd, NDVI_May)
newdata
head(newdata)
tail(newdata)
select(ndvi, -Herd)
select(ndvi, Herd:NDVI_May)
tail(ndvi, 15)
filter(ndvi, Herd == "WAH")
head(popsize)
filter(popsize, Year > 1975, Year <=1980)
filter(popsize, Year %in% c(1980, 1982, 1984, 1986))

popsize %>% Select(Herd) %>% distinct()
